import {
  Dumbbell, Waves, ShieldCheck, Car, Zap, ArrowUpFromDot, Cctv, Baby,
  Building2, Phone, Fence, Wrench, Droplets, Flame, TreePine, Footprints,
  Gamepad2, HeartPulse, Users, Trophy, Crown, Sunset, ConciergeBell,
  ParkingCircle, Home, CircleDot, TreeDeciduous, Dog, Beef, Sparkles,
  BatteryCharging, Cpu, Sun, PartyPopper, type LucideIcon,
} from 'lucide-react';

const amenityIconMap: Record<string, LucideIcon> = {
  'Gym': Dumbbell,
  'Wellness Center': HeartPulse,
  'Swimming Pool': Waves,
  'Infinity Pool': Waves,
  'Water Supply': Droplets,
  '24/7 Security': ShieldCheck,
  'Security': ShieldCheck,
  'CCTV': Cctv,
  'Gated Community': Fence,
  'Covered Parking': Car,
  'Car Parking': Car,
  'Parking': ParkingCircle,
  'Parking Space': ParkingCircle,
  'Power Backup': Zap,
  'Lift': ArrowUpFromDot,
  'Intercom': Phone,
  'Gas Pipeline': Flame,
  'Maintenance Included': Wrench,
  "Children's Play Area": Baby,
  'Clubhouse': Building2,
  'Grand Clubhouse': Crown,
  'Garden': TreePine,
  'Landscaped Garden': TreePine,
  'Jogging Track': Footprints,
  'Indoor Games': Gamepad2,
  'Sports Facilities': Trophy,
  'Sports Court': Trophy,
  'Sports Courts': Trophy,
  'Cricket Box': Trophy,
  'Cricket Stadium': Trophy,
  'Multipurpose Hall': Users,
  'Rooftop Leisure': Sunset,
  'Concierge': ConciergeBell,
  'Independent House': Home,
  'Tennis Court': CircleDot,
  'Amphitheater': Users,
  'Viewing Deck': Sunset,
  'Forest Trails': TreeDeciduous,
  'Treehouses': TreeDeciduous,
  'Pet Park': Dog,
  'BBQ Zone': Beef,
  'Yoga Deck': Sparkles,
  'EV Charging': BatteryCharging,
  'Smart Home': Cpu,
  'Solar Features': Sun,
  'Party Hall': PartyPopper,
  'Crèche': Baby,
};

export function getAmenityIcon(amenity: string): LucideIcon {
  return amenityIconMap[amenity] || ShieldCheck;
}
